
spring.application.name=AdminBankApp

# SQLite Connection
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# PostgreSQL (disabled for now)
#spring.datasource.url=jdbc:postgresql://localhost:5432/testDatabase
#spring.datasource.username=BankAdmin
#spring.datasource.password=yay
#spring.datasource.driver-class-name=org.postgresql.Driver

# Run schema + data.sql properly
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Hot reload for templates
spring.thymeleaf.cache=false


