spring.application.name=AdminBankApp

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

#connect to "database.db" file in root folder.
#spring.datasource.url=jdbc:sqlite:database.db
#spring.datasource.driver-class-name=org.sqlite.JDBC

# Use an absolute path (no ambiguity)
spring.datasource.url=jdbc:sqlite:/Users/lesanduperera/Downloads/ASD/database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never   

#run data.sql file on startup.
#spring.sql.init.mode=always

#hot reload
spring.thymeleaf.cache=false

#spring.jpa.hibernate.ddl-auto=update



