spring.application.name=AdminBankApp

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

#connect do "database.db" file in root folder.
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

#run data.sql file on startup.
spring.sql.init.mode=always

#hot reload
spring.thymeleaf.cache=false

spring.jpa.hibernate.ddl-auto=update

